apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: animal-rescue
commonLabels:
    app.kubernetes.io/name: animal-rescue
    app.kubernetes.io/component: webapi
    app.kubernetes.io/framework: spring-boot-2.3
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    app.kubernetes.io/part-of: animal-rescue
configMapGenerator:
- name: application-configmap
  files:
  - application.yaml
secretGenerator:
- name: animal-rescue-basic
  type: Opaque
  envs:
  - secret.env

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
