apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: animal-rescue

secretGenerator:
- name: ingress-basic-auth
  type: Opaque
  files:
  - auth

resources:
- animal-rescue-ingress.yaml
