apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: springcloudservices/animal-rescue-frontend-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            port: 5000
            path: /
        readinessProbe:
          httpGet:
            port: 5000
            path: /
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
      restartPolicy: Always

